name: Jfrog-called

on:
      
  workflow_call:
    inputs:
        JF_URL:
          required: true
          type: string
        #SONAR_PROJECT_KEY:
          #required: true
          #type: string
    secrets:
        JF_PASSWORD:
          required: true
        JF_ACCESS_TOKEN:
          required: true
          
jobs:
  artifactory:
    runs-on: ubuntu-latest
    
    steps:
#     - uses: actions/checkout@v2
#       with:
#         fetch-depth: 0 #Shallow clones shoud be disabledfor a better relevancy of analysis
#     - name: Setup JDK 11
#       uses: actions/setup-java@v1
#       with:
#         java-version: 11
#     - name: Cache SonarQube packages
#       uses: actions/cache@v1
#       with:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Artifactory 
      uses: actions/download-artifact@v1
      with:
        name: jar-artifact
        path: ./my-app/target/*.jar
    
    - name: Configure jfrog environment
      uses: jfrog/setup-jfrog-cli@v3
      with:
        version: latest
      env:  
        JF_URL: ${{ inputs.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

    - name: Upload APK files to Jfrog
      run: |
        ls -lart
        ls -la ./my-app/target/
        jf rt u --url=${{inputs.JF_URL}} --user=admin --password=${{secrets.JF_PASSWORD}} ./my-app/target/*.jar demo-maven/
 
      

    
            

