name: JFrog-Called
on:
  #workflow_dispatch:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"
      setup:
        required: false
        type: string
        default: ""
      working_directory:
        required: false
        type: string
        default: "."
        

jobs:
  build:
    defaults:
      run:
        working-directory: ${{inputs.working_directory}}

    runs-on: ${{inputs.runs_on}}
    
#   using: "composite"

    steps:
   
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up jfrog
      uses: jfrog/setup-jfrog-cli@v3
      with:
        version: latest
        
    - name: URL check
      uses: jfrog/setup-jfrog-cli@v3
      env:
        JF_URL: https://jfrog.phvr.co.in
        JF_USER: admin
        JF_PASSWORD: Admin@123
        JF_ACCESS_TOKEN: cmVmdGtuOjAxOjE3MTc3Nzc1MzQ6RHZEcHZVR1hPbDdtTGg2bTVWbEFaMUdtNFZy

    
    # Basic authentication credentials
#         JF_URL: ${{ secrets.JF_URL }}
#         JF_USER: ${{ secrets.JF_USER }}
#         JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
#     or
#     # JFrog Platform access token
#     JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

            
        
    - name: Jfrog version
      run: |
       jf --version
       jf rt ping
       
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven 
       
    - name: artifact
      run:
        mvn -B -f ./my-app/pom.xml clean package -DskipTests
       
    - name: Publish JAR artifact to Artifactory
      run: |
        ls -lart
        jfrog rt u --user=admin --password=Admin@123 ./my-app/target/*.jar demo-maven/
 #       jfrog rt u ./my-app/target/*.jar demo-maven --url=https://jfrog.phvr.co.in/artifactory  --user=admin --password=Admin@123
 #       jfrog rt u ./my-app/target/*.jar https://jfrog.phvr.co.in/artifactory/demo-maven/*.jar --url=https://jfrog.phvr.co.in --user=admin --password=Admin@123 --token=cmVmdGtuOjAxOjE3MTc3Nzc1MzQ6RHZEcHZVR1hPbDdtTGg2bTVWbEFaMUdtNFZy
        
