name: main
on:
  workflow_call:

jobs:
  approval:
    name: approval
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ranvivekjan
          issue-title: "Deploying"
          issue-body: "Please approve or deny the deployment"
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''
     # - name: Deploy to production
     #   run: echo deploying
